Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -14,23 +14,25 @@ pipeline {
 
         stage('Build & Deploy Containers') {
             steps {
-                script {
-                    def jenkinsRunning = sh(script: 'docker ps -aq -f name=^jenkins$', returnStdout: true).trim()
-                    if (jenkinsRunning) {
-                        echo "✅ Jenkins container is running. Redeploying app services only..."
+                dir("${env.WORKSPACE}") {
+                    script {
+                        def jenkinsRunning = sh(script: 'docker ps -aq -f name=^jenkins$', returnStdout: true).trim()
+                        if (jenkinsRunning) {
+                            echo "✅ Jenkins container is running. Redeploying app services only..."
 
-                        // Stop and remove only app services
-                        sh """
-                            docker compose stop web db phpmyadmin || true
-                            docker compose rm -f web db phpmyadmin || true
-                        """
+                            // Stop and remove only app services
+                            sh """
+                                docker compose stop web db phpmyadmin || true
+                                docker compose rm -f web db phpmyadmin || true
+                            """
 
-                        // Build and start app services
-                        sh "docker compose up -d --build web db phpmyadmin"
-                    } else {
-                        echo "⚠️ Jenkins container not found. Bringing up all services..."
-                        sh "docker compose down || true"
-                        sh "docker compose up -d --build"
+                            // Build and start app services
+                            sh "docker compose up -d --build web db phpmyadmin"
+                        } else {
+                            echo "⚠️ Jenkins container not found. Bringing up all services..."
+                            sh "docker compose down || true"
+                            sh "docker compose up -d --build"
+                        }
                     }
                 }
             }
